### ISSUE TITLE
java.lang.IllegalArgumentException: JClass name 3 contains illegal character for beggining of identifier: 3

### ISSUE THREAD

**Issue by pesjak** [HexarA/Json2Pojo#12]
I'm getting this exception when trying to use your plugin.

**Comment by HexarA** [comment]
What's the input JSON?

**Comment by pesjak** [comment]
```
"location":{
      "13":{
         "id":"13",
         "text":"Berlin",
         "position":"1",
         "option":{
            "216":{
               "id":"216",
               "text":"Ve",
               "position":"2",
               "default":"1",
               "option":false
            },
            "198":{
               "id":"198",
               "text":"Berad",
               "position":"0",
               "default":"0",
               "option":[
                  {

```
etc. about 20k of code

**Comment by HexarA** [comment]
Aha. So the plugin tool works by translating property names into Java classes so that the properties can be serialized into those classes, but in Java, class names cannot be numeric like "13" or "216". It seems a bit unconventional to me to have fully-numeric property names like you have here - see [Google JSON Style Guidelines](https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Guidelines). 

Regardless, any ideas as to what would be a good solution? Should the tool rename fully-numeric property names like "13" into "Class13" or something? Or perhaps could your JSON data be re-structured to not use numeric keys?
