### ISSUE TITLE
@SerializedName Annotations For Builder Member Variables

### ISSUE THREAD

**Issue by samcaplat** [HexarA/Json2Pojo#9]
When using the Builder Pattern to create JSON through Gson, the member variables for the Builder do not serialise in the correct format. I'm currently copy/pasting the automatically generated @SerializedName annotations to the Builder to solve this problem, but it would be great if the annotation could be automatically generated for the Builder as well.

Simple example here, as you can see the Car member variable has an annotation, but the Builder member variable doesn't:

```
public class Car {

    @SerializedName("has_wheels")
    private Boolean mHasWheels;

    public Boolean getHasWheels() {
        return mHasWheels;
    }

    public static class Builder {

        private Boolean mHasWheels;

        public Car.Builder withHasWheels(Boolean hasWheels) {
            mHasWheels = hasWheels;
            return this;
        }
    }
}
```

**Comment by HexarA** [comment]
Hi Sam! Thanks for your interest in my plugin / project.

I took a look at the issue you raised and you’re right, the member variables for the Builder don’t have @SerializedName annotations. Perhaps I am wrong, but I wonder if these annotations for the Builder are truly necessary? Generally speaking, if you are serializing an object from source JSON into a POJO via GSON, the builder itself won’t be used because GSON will set the fields directly based on the @SerializedName annotations. Similarly, if you are serializing a POJO into JSON via GSON, you just need to make sure the fields are set correctly before you serialize, which you can use via the Builder withX methods. There’s no need to also serialize the internal Builder class, unless I am mistaken ;)

Does that make sense? Or is it possible that I am incorrect in my assessment?

**Comment by HexarA** [comment]
I've responded via email, but I think I'm going to close this issue here as I don't think it is necessary to add annotations to the builder classes. Assuming source JSON text of:

```
{
  "results": [
    {
      "id": "12345"
    }
  ]
}
```

And a root class named SomethingRoot, you should be able to either deserialize source JSON or construct your own classes with builders for serialization like so:

```
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import models.Result;
import models.SomethingRoot;

import java.util.Collections;

public class Main {

    private static final String JSON = "{\n" +
            "  \"results\": [{\n" +
            "    \"id\": \"12345\"\n" +
            "  }]\n" +
            "}";

    public static void main(String[] args) {
        // Deserialize JSON and print result
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        SomethingRoot somethingRoot = gson.fromJson(JSON, SomethingRoot.class);
        System.out.println(gson.toJson(somethingRoot));

        // Build an object and print result
        Result result = new Result.Builder().withId("12345").build();
        SomethingRoot built = new SomethingRoot.Builder().withResults(Collections.singletonList(result)).build();
        System.out.println(gson.toJson(built));
    }
}
```
